---
- name: Send notification message via Rocket Chat
  rocketchat:
    token: "{{ rocketchat_token }}"
    domain: "{{ rocketchat_domain }}"
    channel: "{{ rocketchat_channel }}"
    username: "{{ rocketchat_username }}"
    msg: 'Starting OpenShift Cluster maintenance on node {{ inventory_hostname }}'
  delegate_to: localhost
