---
- name: Install yum-utils to have needs-restarting available
  yum:
    name: yum-utils
    state: installed

- name: Check for reboot hint
  command: needs-restarting -r 
  ignore_errors: true
  register: reboot_hint
  check_mode: false
  changed_when: false

- debug:
  var: force_reboot

- name: Reboot
  shell: sleep 2 && /usr/sbin/shutdown -r now "Reboot required for updated kernel or libraries"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_hint.rc != 0 or force_reboot == 'true'

